language: elixir
elixir:
  - 1.7
  - 1.8
  - 1.9
env:
  - MIX_ENV=test
before_script:
  - mix compile --warnings-as-errors
  - mix deps.get
script:
  - mix coveralls.travis
  - mix dialyzer
cache:
  directories:
    - _build
    - deps